apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: environ-initializer
  namespace: cluster-addons
  labels:
    role: initializer
spec:
  replicas: 1
  template:
    metadata:
      name: environ-initializer
      labels:
        role: initializer
    spec:
      serviceAccountName: environ-initializer
      containers:
      - name: environ-initializer
        image: quay.io/lander2k2/environ-initializer:ds
        args: ["-namespace", "cluster-addons"]
        imagePullPolicy: Always

