apiVersion: v1
kind: ServiceAccount
metadata:
  name: environ-initializer
  namespace: cluster-addons

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: initialize-deployments
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: environ-initializer
subjects:
- kind: ServiceAccount
  name: environ-initializer
  namespace: cluster-addons
roleRef:
  kind: ClusterRole
  name: initialize-deployments
  apiGroup: rbac.authorization.k8s.io

