apiVersion: v1
kind: ConfigMap
metadata:
  name: environ-initializer-config
  namespace: cluster-addons
data:
  http-proxy: |
    envVars:
    - name: HTTP_PROXY
      value: http://proxy.example.com
    - name: HTTPS_PROXY
      value: http://proxy.example.com
    - name: NO_PROXY
      value: 127.0.0.1,localhost,.example.com,10.3.0.1,.cluster.local
  service-x: |
    envVars:
    - name: SERVICE_URL
      value: service.example.com

